# Welcome to Blackdoe Online Resume!

title: Online Resume
authorName: Gary
email: gary@garyllewellyn.us
description: > # this means to ignore newlines until "baseurl:"
  This is my online Resume.
baseurl: "" # empty for root site
url: "https://resume.garyllewellyn.us/"
twitter_username: wedi_blino
github_username: taffo73

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

host: 0.0.0.0

published: true
future: true
